### ISSUE TITLE
Iter_Free

### ISSUE THREAD

**Issue by kadaradam** [pawn-lang/YSI-Includes#109]
`Iter_Free()` returns `cellmin,` instead of `-1` when it's full. Is this on purpose?

**Comment by Southclaws** [comment]
I always assumed it returned -1, that check is littered all over SIF and SS!

https://github.com/Misiur/YSI-Includes/blob/YSI.tl/YSI_Data/y_foreach/impl.inc#L1105

Would this break much in the way of compatibility if changed to return -1? `Iter_FreeMulti_Internal` already returns -1 so I assume this is just a typo.

**Comment by Misiur** [comment]
Yes, that's on purpose (changed around when Y_Less added custom iterators)

(https://github.com/Misiur/YSI-Includes/commit/128afdb767eec60b7913f352a9f0c08ddf096725 - lumped somewhere in this commit)

**Comment by Y-Less** [comment]
The functions do seem a little inconsistent in return values, and I honestly don't know why...

**Comment by Y-Less** [comment]
`Random` and `Add` return `cellmin`, but `Get` returns `-1` and `Free` uses both...

**Comment by Southclaws** [comment]
Every check I've ever written looks like this: https://github.com/Southclaw/SIF/blob/master/SIF/Button.pwn#L480-L482 but I've never actually noticed this problem because I've never hit the limits for these objects until recently. It would be great if this could be changed back to `return -1;` so I don't need to replace all [these](https://github.com/Southclaw/ScavengeSurvive/search?utf8=%E2%9C%93&q=Iter_free) [checks](https://github.com/Southclaw/SIF/search?utf8=%E2%9C%93&q=Iter_free) to `if(id == cellmin)`.

**Comment by Y-Less** [comment]
There is really no reason in normal iterators to prefer one over the other.  Special iterators do use `cellmin` because they may return `-1` as a valid value - they may actually return any value as a valid one, but some value needs to be special and since `cellmin` has no positive equivalent it is somewhat special (and doesn't print correctly).

But you are right that the other functions should all return `-1` (or should all return the same thing).

**Comment by Y-Less** [comment]
Actually, they should all return `ITER_NONE` or similar and leave what that value actually is as an implementation detail.

**Comment by Southclaws** [comment]
That would actually make a lot more sense, looking at my code searches I do have some inconsistencies where I'm comparing to -1 sometimes and some constant that's presumably -1 other times.

**Comment by Y-Less** [comment]
Especially since one improvement that I would love to make, if I can ever figure out how to integrate it seamlessly, is offsets:

``` pawn
new Iterator:iter<100, +7>; // Iterator from 7 - 106.
new Iterator:vid<211, +400>; // Iterator from 400 to 611.
new Iterator:playerVehicles<MAX_PLAYERS, 211, +400>;
```

Ignore the syntax.  But for that to work with negative offsets, -1 suddenly becomes a valid value in iterators.  Again, any value does, but -1 is far more likely to be used than cellmin.

**Comment by Y-Less** [comment]
Actually, not all the functions even return one of those two values on failure.  The actual code in the `foreach` macro depends strongly on a failure of `>= Iter_Size(iterator)`.  This is because of the data layout - the list is circular with extra data at the end of the array for the start points.  When the loop gets back to that point it is finished.  This fact is also used by `Contains` - all lists are forwards, so any element whose value is larger than its slot position is in the iterator, so the last valid value in the iterator can't point to -1.

And I just realised my earlier offset vehicle ID example was wrong as they are clearly model IDs not vehicle IDs.  But the point still stands (with a leaning towards `new Iterator:a<10--20>` syntax).

**Comment by Y-Less** [comment]
Just did this - changed all the relevant returns to (cellmin).  Actually, when I did it I couldn't find this issue and had forgotten what symbol we had agreed on so used `INVALID_ITERATOR_SLOT`, but now I've added `ITER_NONE` as well.  I honestly thought this had been done a long time ago and forgotten about.
