### ISSUE TITLE
calling commands

### ISSUE THREAD

**Issue by preguntator** [pawn-lang/YSI-Includes#112]
Hello, 

How can i call commands such as zcmd  with y_commands: 
cmd_register(playerid, params)

And how i can make use of `W@("OnPlayerCommandPerformed", "is", player1, cmd);` for making a player use a command

I thank you

**Comment by Crayder** [comment]
```
//playerid, I'm not sure
BroadcastCommand(%0,%1) CallLocalFunction("OnPlayerCommandText","is",%0,%1)

#define Y_COMMANDS_NO_IPC 
#include <YSI\y_commands>
```

I never actually tried this in YSI 4 though.

**Comment by Y-Less** [comment]
The simplest way is with the `call` macro:

``` pawn
call OnPlayerCommandText(playerid, "/whatever");
```

Or `Command_ReParse` - there is no real direct way of doing it because you shouldn't need to.  If you have two commands that you want to do the same thing, either abstract that functionality out in to a dedicated function, or use `Command_AddAlt` (or `Command_AltName`, I forget which) to actually add the second name as a true alias instead of a wrapper.

As for commands, y_commands has a built-in permissions system so you don't need to use `OnPlayerCommandPerformed`, which was mostly added for ZCMD compatability.  Instead, use `Command_SetPlayer(YCMD:whatever, playerid, false);` to disable a command for a player.  For even better permissions, use y_groups, which wraps the command permissions system (and many others) to allow you to manipulate groups (teams/admin levels/factions etc) all at once.

**Comment by preguntator** [comment]
I could use `Command_SetPlayer(YCMD:whatever, playerid, false);` however for something in my gamemode, I need to disable the entire use of commands for some people ? Is There any possibilities to do it while currently I use : `public OnPlayerCommandReceived(playerid, cmdtext[])`

**Comment by Y-Less** [comment]
Yes, as I said, groups.

**Comment by preguntator** [comment]
Okay, using groups seems to be the better solutions however, let's imagin that i wanna disable **all** commands of my gamemode, does i have to disabled all my this method

**Comment by Y-Less** [comment]
This is a little awkward, but not terribly.  Create a new group, add all commands to that group, then in `OnScriptInit` add:

``` pawn
Groups_SetCommandDefault(false);
```

Which will disable all commands for all players by default, then having them in your custom group will re-enable them for all players.  If you want to disable everything, remove the player from that global group.

**Comment by Y-Less** [comment]
I know it is slightly awkward - it is a common feature I should have made easier frankly!  But you can then create another "disabled" groups and add things like `/appeal` or whatever to it, so muted/blocked players can still use some commands.

**Comment by preguntator** [comment]
I see ! Thanks
