### ISSUE TITLE
Updating AMX Assembly

### ISSUE THREAD

**Issue by Crayder** [pawn-lang/YSI-Includes#116]
Just asking because I wasn't sure, will updating the AMX assembly includes corrupt anything in YSI? The branch referenced here is pretty old.

**Comment by Crayder** [comment]
Dumb question since just a few weeks ago Y-Less added a commit that tells us to update... -.-

**Comment by Y-Less** [comment]
Did you just open a question, reply to it yourself, and call it dumb?  I saw the e-mails come through and without noticing the poster's names just assumed it was two different people by the tones...

**Comment by Y-Less** [comment]
Can I close this?  In real answer to your question - although YSI has already made a submodule reference to amx_assembly, in truth I never really knew how to use them seamlessly, so that was never updated and I always used the latest version from github.  So if there are any incompatabilities I don't know about them and never saw them in unit tests.

**Comment by Crayder** [comment]
Lol... Yes, I was responding to my own stupidity. I could've took the second to investigate before I posted.

And I thought I already closed this.
