### ISSUE TITLE
MySQL R40 & YSI

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#121]
Since the new release of R40 there has been issues with YSI some includes. I am not sure if its y_hooks but I would appreciate your help. Maddinator said the following to me:

> The callback index for OnVehicleLoad is 456. When trying to execute that callback:
> 
> ```
> [09/06/16 05:34:30] [DEBUG] executing AMX callback with index '456'
> [09/06/16 05:34:30] [DEBUG] AMX callback executed with error '20'
> ```
> 
> Error 20 is the "invalid index" error. However, a little bit later:
> 
> ```
> [09/06/16 05:34:30] [DEBUG] CCallback::Create - callback index for 'OnVehicleLoad': 387
> ```
> 
> The index changed. Just so you know, the index is hardcoded in a "public function table" in the .amx file. There are libraries which can change that table during runtime though, and that's where y_hooks probably gets in.
> Your code worked with R39-6, because the public function index was retrieved just before executing the public function. In R40 however, the callback index is retrieved in mysql_tquery. This way mysql_tquery can directly indicate an error (return 0), if that callback doesn't exist.

So, it seems like the index for "OnVehicleLoad" changes after OnGameModeInit finished executing. And since you said you're hooking OnGameModeInit, I'd guess it has something to do with y_hooks. So this is not a MySQL plugin problem, but a y_hooks one. You can probably workaround this by executing the query per timer, e.g.

```
public OnGameModeInit()
{
    //...
    SetTimer("_workaround_LoadVehicles", 0, false);
}

forward _workaround_LoadVehicles();
public _workaround_LoadVehicles()
{
    mysql_tquery(g_SQL, "SELECT * FROM vehicles", "OnVehicleLoad");
    return 1;
}
```

Anyway, you can look into this @Y-Less, @Misiur

**Comment by Y-Less** [comment]
This isn't a MySQL plugin problem, but I also wouldn't call it a YSI problem per-se. The problem is two different systems making assumptions that on their own are fine, but cause problems when combined.

YSI does a lot of public function manipulations, but they all happen in `OnScriptInit` and should be completed long before and user code gets run.  Is this in an include called before YSI?  If so, your best bet might to make sure that the first includes are:

``` pawn
#include <a_samp>
#include <fixes> // If you use it.
#include <YSI\y_hooks>
// Everything else.
``

That's the only reason I can see at the minute for why that code would happen before the header shuffle happens.
```

**Comment by Y-Less** [comment]
This isn't a MySQL plugin problem, but I also wouldn't call it a YSI problem per-se. The problem is two different systems making assumptions that on their own are fine, but cause problems when combined.

YSI does a lot of public function manipulations, but they all happen in `OnScriptInit` and should be completed long before and user code gets run.  Is this in an include called before YSI?  If so, your best bet might to make sure that the first includes are:

```pawn
#include <a_samp>
#include <fixes> // If you use it.
#include <YSI\y_hooks>
// Everything else.
``

That's the only reason I can see at the minute for why that code would happen before the header shuffle happens.

**Comment by Y-Less** [comment]
This isn't a MySQL plugin problem, but I also wouldn't call it a YSI problem per-se. The problem is two different systems making assumptions that on their own are fine, but cause problems when combined.

YSI does a lot of public function manipulations, but they all happen in `OnScriptInit` and should be completed long before and user code gets run.  Is this in an include called before YSI?  If so, your best bet might to make sure that the first includes are:

```pawn
#include <a_samp>
#include <fixes> // If you use it.
#include <YSI\y_hooks>
// Everything else.
``

That's the only reason I can see at the minute for why that code would happen before the header shuffle happens.

**Comment by xFirez** [comment]
That worked, thank you very much :).

**Comment by xFirez** [comment]
That worked, thank you very much :).

**Comment by ghost** [comment]
That worked, thank you very much :).

**Comment by PT-Player** [comment]
@Y-Less sorry for open thins again but take an look i need an fast explain..

you said this

`#include <a_samp>
#include <fixes> // If you use it.
#include <YSI\y_hooks>
// Everything else.`

now i ask about the streamer not should be this..

`#include <a_samp>
#include <fixes> // If you use it.
...... streamer <
#include <YSI\y_hooks>
// Everything else.`

because YSI have some checks to the streamer like the ammount of defined objects etc..

Say me the best to use the YSI..

Thanks in advance and sorry all
