### ISSUE TITLE
undefined symbol "_ALS_go"

### ISSUE THREAD

**Issue by Dayvison** [pawn-lang/YSI-Includes#122]
``` pawn
#include <a_samp>
#include <YSI\Any YSI file>

public OnGameModeInit()
{
    return 1;
}
main() {
    // Just example
    OnGameModeInit();
}
```

Give me errors:

```
 error 017: undefined symbol "_ALS"
 error 029: invalid expression, assumed zero
 error 017: undefined symbol "_ALS_go"
fatal error 107: too many error messages on one line
```

**Comment by Y-Less** [comment]
Don't call callbacks directly like that.  Use `CallRemoteFunction` or `CallLocalFunction` or the `call OnWhatever()` macro.

**Comment by Dayvison** [comment]
Ok, i made what i need like that:

* include a_samp
* hook OnGameModeInit(not by yhooks obviously xD)
    * Call a function to be called before any other
* include YSI and another librarys
* ...

**Comment by Y-Less** [comment]
There are native ways of doing that.  In fact, there's no guarantee that your function will be called before y_hooks, since it does low-level rewrites at run-time, so they tend to be called before ALS hooks even when they appear after them in the source code.  The only guarantee is that a y_hook in a file will be called after y_hooks in any of its includes.  fixes.inc is designed to be called before any y_hooks hooks, and doing so took a special hook method in that file AND extra code in y_hooks to detect that case and allow it.

**Comment by Y-Less** [comment]
Actually, this might work for `OnGameModeInit`, but only that (and `OnFilterScriptInit`) because they are ALS hooks not y_hooks (since the library isn't initalised yet).  I say "may", because even that is potentially dangerous depending on what you are doing - hooks before YSI can break y_malloc and all dependent libraries, y_hooks rewrites the AMX header so anything non-trivial might break, and there are other libraries that do code modifications before everything else runs.
