### ISSUE TITLE
[y_commands]Command_AddAltNamed special characters

### ISSUE THREAD

**Issue by MadRoxx** [pawn-lang/YSI-Includes#13]
![image](https://cloud.githubusercontent.com/assets/12086557/7562002/ee873da2-f7d0-11e4-9b0a-9b743d983add.png)

![image](https://cloud.githubusercontent.com/assets/12086557/7562013/09e1e4c6-f7d1-11e4-8a77-7ae3087de92d.png)

When i type alt-named version of a command (only with special characters), i give `COMMAND_UNDEFINED` error. Other alt-named commands work fine.

**Comment by Misiur** [comment]
I'm not certain what the cause is, it might either be PAWN specific, y_hashmap limitaton, or something completely different. I don't have much time lately, so I'm not certain if I'll get around to it. Also, do you know if this bug was present in YSI 3?

**Comment by Misiur** [comment]
Found it: [This is the root cause.](https://github.com/Misiur/YSI-Includes/blob/0b6ebda6214c1b91a6543c067bd848cb9a03c908/YSI_Coding/y_stringhash.inc#L296)

**Comment by Y-Less** [comment]
I don't actually think that's the root cause.  I've only had a quick glance since I'm trying to help less and just encourage others to get to know the code, but looking at it this is my fault.  "Command_AddAlt" hashes the string (using bernstein, that comment you highlighted only applies for compile-time string hashes and the first character of a string at run-time), but "Command_ReProcess" does a slightly different hash.  It converts:

```
rádióhangolás
```

To:

```
rdihangols@s4ai1u
```

Using standard punycode, but with "@" instead of "-", while hashing that result.  So "Command_AddAlt" needs to do that encoding instead.  This is because y_commands has a feature so secret that even I forgot about it!  You can declare commands with punycode:

``` pawn
YCMD:rdihangols@s4ai1u(playerid, params[], help)
{
}
```

Is equivalent to:

``` pawn
YCMD:rádióhangolás(playerid, params[], help)
{
}
```

But will compile.

**Comment by Y-Less** [comment]
There are punycode converters online, but most will prefix the result with "xn--" and separate the two parts with "-", because that is how they are used in internationalised domain names.

**Comment by Misiur** [comment]
Welp, I'm wrong again. Being puny human ain't easy. So, applying `Puny_EncodeHash` into addalt is the way to go?

**Comment by Y-Less** [comment]
Probably, as I said that was just a cursory glance.

**Comment by MadRoxx** [comment]
Hello again, i tested with [This](https://github.com/Misiur/YSI) version of YSI and now works.

**Comment by Misiur** [comment]
Ok, just keep in mind that master is 3, and there are many improvements in 4 (though as we can see with occasional bugs). Keep an eye on this issue, and upgrade when we resolve this.

**Comment by MadRoxx** [comment]
Ok, i wait for updates, and thanks for the help :)

**Comment by MadRoxx** [comment]
something? :question:

**Comment by Misiur** [comment]
Well, I tried a lot of stuff today, but I can't seem to get it working properly. One major problem is with `Command_Find`, as from simple hashmap lookup it went to 

``` pawn
foreign Command_Find(string:cmd[]);

global Command_Find(string:cmd[])
{
    static
        sCmd[64] = "",
        sHash;

    Puny_EncodeHash(sCmd, cmd, sHash, .delimiter = '@');

    return HashMap_GetWithHash(YSI_g_sCommandMap, sCmd, sHash);
}
```

This is not something we want for every command lookup (performance wise). I'll fiddle with it some more tommorow, maybe I've overlooked something.

**Comment by Misiur** [comment]
Ok, tests pass so I guess https://github.com/Misiur/YSI-Includes/commit/e0a905101228d2a76207dcc191fe08cdabf9853d solves this for you. In case performance deteriorates too much we'll have to think more about this.
