### ISSUE TITLE
Size of Vehicle/LocalVehicle iterators.

### ISSUE THREAD

**Issue by Konstantinos-Sk** [pawn-lang/YSI-Includes#130]
https://github.com/Misiur/YSI-Includes/blob/YSI.tl/YSI_Data/y_foreach/iterators.inc#L244-L250

The size for each one of those two iterators is 2001 but only 1999 vehicles can be created so the last index is unusable to both.

**Comment by Y-Less** [comment]
They have a `+ 1` because the lowest vehicle ID is 1 not 0, so the first slot is never used.  It does make sense though that if `MAX_VEHICLES` is 2000, then the highest ID would be 1999 so that they could fit in an array of size `[MAX_VEHICLES]`.  Are you certain about this (it's not something I knew).

**Comment by Konstantinos-Sk** [comment]
Yes, I am. The limit is 1999 _created_ vehicles.

**Comment by Y-Less** [comment]
Seems like a pretty easy fix then.  Want to make a pull request?

**Comment by Y-Less** [comment]
Thanks.
