### ISSUE TITLE
.

### ISSUE THREAD

**Issue by MaxAndolini** [pawn-lang/YSI-Includes#138]
.

**Comment by Misiur** [comment]
It's not an issue with y_va, as even the letters you've inserted with `strins(str, "(( {2ECC71}BİLGİ: {FFFFFF}", 0);` got mangled to `(( {2ECC71}B0LG0: {FFFFFF}`. I haven't worked with utf characters, ask on forums for more info.

**Comment by MaxAndolini** [comment]
stock SendInfoMessage(playerid, const fmat[], va_args<>)
{
    new
        str[145];
    va_format(str, sizeof(str), fmat, va_start<2>);
    /*strins(str, "(( {2ECC71}BİLGİ: {FFFFFF}", 0);
    strins(str, " {34495E}))", strlen(str));*/
	printf(str);
    return SendClientMessage(playerid, 0x34495EFF, str);
}

Same

[16:41:50] 0sim ~w~Gıda Dağıtımı

**Comment by Crayder** [comment]
@MaxAndolini NEVER delete your issue like that! Now other people won't know what happened when it happens to them, no matter how unlikely it is...

**Comment by MaxAndolini** [comment]
Its not issue its my fault.

**Comment by Crayder** [comment]
@MaxAndolini but what if other people come across the same thing, the same thing you did?

**Comment by Y-Less** [comment]
I'm slightly torn on this.  @Crayder is right in that in general you should not delete questions after getting a solution, and even if you figure it out yourself you should go back and post your discovered answer for others in the future.  However, @MaxAndolini is also right in that this isn't the right place for general help, even help with using YSI; this is for reporting bugs within YSI itself, and if your problem turns out to be your own fault then that's sad but not an "issue" for here (I will still generally try to help though, because why not).  You are both sort of right, so probably best to just leave it as-is.

**Comment by Y-Less** [comment]
Of course the real place for things like that would be the official YSI topic, but some idiotᵐᵉ deleted that, so I guess I shouldn't be surprised that there's no other place...
