### ISSUE TITLE
Y_iterate - local iterator Vehicle

### ISSUE THREAD

**Issue by BenBout** [pawn-lang/YSI-Includes#158]
Is the local iterator "Vehicle" bugged ?

```
stock DestroyAllPlayerVehicle(playerid){
	
	foreach(new vehid : Vehicle) if(vData[vehid][vUser] == playerid){
		
		printf("loop vehid %i", vehid);
		vData[vehid][vUser] = INVALID_PLAYER_ID;
		DestroyVehicle(vehid);
	}
}
```

tested with 1 vehicle spawned, result : an infinite loop.

**Comment by Y-Less** [comment]
No, but you can't remove things from an iterator inside the iterator.

**Comment by BenBout** [comment]
Oh yeah, you are wright, sorry for this post. Thank you.

**Comment by Y-Less** [comment]
I should note that `Kick` is handled specially, so that you can kick all players in a loop without it hanging, but this isn't (and getting all cases is non-trivial).  The best way would be:

```pawn
for (new i = Iter_Start(Vehicle), j, end = Iter_End(Vehicle); i != end; i = j)
{
    j = Iter_Next(Vehicle, i);
    DestroyVehicle(i);
}
```

That will advance the iterator before destroying the vehicle, thus not leaving the iterator in an invalid state.
