### ISSUE TITLE
Y_text issue and Y_dialog is not calling response while using gmx

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#159]
Good morning, 

I'm seriously looking at y_text for my servers: But I met an issue: I sometimes use TextDrawSetString which I'd like to use it in y_text so translate what i say in. How could I include this in y_text

Thanks for your help

**Comment by ghost** [comment]
I'm adding an issue: Indeed, when i use y_dialog. I can notice that when I use /rcon gmx: My login player is not calling dialog response. As a consequence, the dialog disappear when inserting the password: But, you are not logged in: 

https://gist.github.com/ant298/cb6a8862236180ca33c9fb212d94dc75

**Comment by Y-Less** [comment]
gmx isn't meant to call dialog responses.

**Comment by ghost** [comment]
Sorry, I explain certainly wrongly: I mean when my server is running: I use /rcon gmx: Players are reconnecting then My dialog (as shown in gist) wont call inline function for dialog responses

**Comment by Y-Less** [comment]
Have you tried with the y_malloc array implementation?  y_inline uses that for closures and there have been issues reported before with the heap implementation (which isn't surprising since it did exploit some bugs).  It will make your mode bigger, since it puts the allocation memory in a global array instead of a dynamic array, but should work OK.

**Comment by ghost** [comment]
Using it for y_dialog ? What do you mean ? I'm sorry i don't really see

**Comment by Y-Less** [comment]
y_dialog relies on y_malloc.  y_malloc had a long-standing GMX bug where it just wouldn't work sometimes on some systems after a restart.  So I added a second implementation (actually the original implementation) which uses a big array instead of a heap hack.

**Comment by ghost** [comment]
Okay, I begin to see Using #define YSI_NO_HEAP_MALLOC  if I'm not wrong **OR** find an old commit from you using the big array ?

**Comment by Y-Less** [comment]
The latest code uses the array if you have that define. Don't use an old commit.

**Comment by ghost** [comment]
I will give a try with YSI_NO_HEAP_MALLOC and let you know. Thanks

**Comment by ghost** [comment]
I have tried now. It is working: response is called with YSI_NO_HEAP_MALLOC: thanks even if you were right my mode dobled his size: thanks for the fast help !

**Comment by Y-Less** [comment]
y_malloc works by using a single huge array and apportioning out parts when requested with `malloc`, and returning them with `free`.  PAWN does have a heap, which is used for things like returning strings from functions and passing numbers by reference to functions.  It isn't truly dynamic memory, but it is allocated when the mode starts.  I found a bug in the VM implementation of heap allocation in conjunction with repeated `HALT`s (a p-code opcode) and exploited that bug to essentially shrink the heap and keep part of it private for myself.  In that private part is where y_malloc gets its memory for allocations, which means that because the memory is allocated at mode startup, it isn't in the AMX.  However, because this is exploiting bugs it proved to be not fully stable (not really surprising) and didn't work with the JIT plugin (but still other parts of YSI don't either).  Before I found the bug, y_malloc just used a large global array, which (because AMX files don't have a .BSS segment) is always included in the compiled file, even if it is all zeros, to represent the initial values of the array.  Sadly this means that if you fall back to that version the huge array is compiled in statically and bloats your mode (but will compress VERY well for uploads).

Mode size has always been a big complaint about YSI; though I personally don't think it is at all as big a problem as most people claim.  I'm pretty sure that the modes people build and complain about are smaller than the web pages they are complaining about them on, and will still take mere seconds to upload).  Anyway, the heap allocation method was an attempt to vastly reduce the file sizes, but it failed.  I could also do more - some libraries use a lot of memory in globals at startup, but then never use it again.  If I could get that on to the stack they would be excellent reductions.

**Comment by Y-Less** [comment]
Also, to answer your first question:

```pawn
Text_Render(playerid_or_set, $TEXT_NAME, format, parameters);
TextDrawSetString(td, Text_GetPreRender(Langs_GetPlayerLanguage(playerid)));
```

It is done in two stages because it vastly reduces the work done when using multiple players:

```pawn
// Render once in all used languages, cache the results.
Text_Render(ALL_PLAYERS, $TEXT_NAME, format, parameters);
foreach (new pid : Player)
{
    PlayerTextDrawSetString(td[pid], Text_GetPreRender(Langs_GetPlayerLanguage(pid)));
}
```

That will just do the expensive formattings once per language, then retrieve the results for each player.  If you know y_groups and y_playerset this can vastly reduce the amount of work done for things like sending messages to all online admins in their own language etc.

**Comment by ghost** [comment]
I'm also using DYNAMIC_MEMORY for y_malloc. hoping it wont impact this new way for using y_malloc

**Comment by Y-Less** [comment]
No, it shouldn't - they both support that, though in different ways (and there are quite a few tests now for both).
