### ISSUE TITLE
y_text doesn't support dialogs?

### ISSUE THREAD

**Issue by PatchwerkQWER** [pawn-lang/YSI-Includes#17]
Hi, from the code it looks like it was prepared for dialogs but it's not finished. So I have question for @Y-Less - y_text support dialogs? or?

https://github.com/Misiur/YSI-Includes/blob/YSI.tl/YSI_Players/y_text/styles.inc#L207

https://github.com/Misiur/YSI-Includes/blob/YSI.tl/YSI_Players/y_text/render.inc#L129

Thanks

**Comment by Y-Less** [comment]
No, y_dialogs supports dialogs and y_text supports text...

**Comment by PatchwerkQWER** [comment]
Okay, thanks I find it. 
https://github.com/Misiur/YSI-Includes/blob/0b6ebda6214c1b91a6543c067bd848cb9a03c908/YSI_Extra/y_extra_users.inc#L57
and
https://github.com/Misiur/YSI-Includes/blob/0b6ebda6214c1b91a6543c067bd848cb9a03c908/YSI_Players/y_text.inc#L244

Thanks for your time

**Comment by PatchwerkQWER** [comment]
Sorry but I have errors with this code
Text_MessageBox(playerid, using inline Response, $YSI_TELS_TELE, $YSI_SELL_HELP, $DIALOG_OK, $DIALOG_CANCEL);  

Errors:
tett.pwn(40) : error 029: invalid expression, assumed zero
tett.pwn(40) : error 017: undefined symbol "YSI_SELL_HELP"
tett.pwn(40) : error 029: invalid expression, assumed zero
tett.pwn(40) : fatal error 107: too many error messages on one line

Any ideas, why it doesn't work? :)

Thanks

**Comment by PatchwerkQWER** [comment]
Testing code:
http://pastebin.com/ePJv5q2d

@Y-Less Do  you know where problem is?

**Comment by PatchwerkQWER** [comment]
Okay, I find the reason why it doesnt work! I replace this https://github.com/Misiur/YSI-Includes/blob/YSI.tl/YSI_Players/y_text.inc#L230 with this "#define DO_MOVE|||%0ŁŁŁ %0DO_MOVE|||" (from YSI 3.1) and it works! @Y-Less what do you think, it is the reason why it doesn't work?

**Comment by Y-Less** [comment]
That really shouldn't work!  The "£££" syntax was changed for "$$$" because "£" is not an ASCII symbol and caused some problems (though also revealed a compiler bug IIRC).    These lines:

https://github.com/Misiur/YSI-Includes/blob/f4d85a8d1c7552618c0546d3f93d5ef625ed59c5/YSI_Players/y_text.inc#L244-L248

All use "$" so I can't see why it would work otherwise.

Can you compile with "-l" and post the output of your text lines please?

**Comment by PatchwerkQWER** [comment]
Here is the output - http://www.solidfiles.com/d/2678e52921

**Comment by Y-Less** [comment]
Thanks, I now know EXACTLY why this happens!  There was a reason I used "£££" not "$$$" originally, then I forgot that when I changed over because of the other problems with "£££".

**Comment by PatchwerkQWER** [comment]
Well, it should be "ŁŁŁ" or "$$$" because Im lost

**Comment by Y-Less** [comment]
Neither.  It can't be `£££` because that isn't an ASCII character, and it can't be `$$$` because that conflicts with the `$` in the text names (both use that symbol because it isn't used elsewhere).  Try replace all the instances of `$$$` with:

``````
```
``````

That's the backtick, not the standard apostrophe, as it IS ASCII and ISN'T used elsewhere in PAWN.  By my count, there are 19 instances of `$$$` to replace.

**Comment by PatchwerkQWER** [comment]
Nice, It works. http://prntscr.com/7cmxtv 
Edited code:
    #define DO_MOVE|||%0``` %0DO_MOVE|||

and

``````
#define Text_MessageBox(%0,%1,%2,%3,%4,%5) PSF:_Text_DialogBox(%0,DIALOG_STYLE_MSGBOX,%1,DO_TEXT_SET:%2 DO_MOVE|||,DO_TEXT_SET:%3 ```,DO_TEXT_SET:%4 ```,DO_TEXT_SET:%5 UN```)
#define Text_InputBox(%0,%1,%2,%3,%4,%5) PSF:_Text_DialogBox(%0,DIALOG_STYLE_INPUT,%1,DO_TEXT_SET:%2 DO_MOVE|||,DO_TEXT_SET:%3 ```,DO_TEXT_SET:%4 ```,DO_TEXT_SET:%5 UN```)
#define Text_ListBox(%0,%1,%2,%3,%4,%5) PSF:_Text_DialogBox(%0,DIALOG_STYLE_LIST,%1,DO_TEXT_SET:%2 DO_MOVE|||,DO_TEXT_SET:%3 ```,DO_TEXT_SET:%4 ```,DO_TEXT_SET:%5 UN```)
#define Text_PasswordBox(%0,%1,%2,%3,%4,%5) PSF:_Text_DialogBox(%0,DIALOG_STYLE_PASSWORD,%1,DO_TEXT_SET:%2 DO_MOVE|||,DO_TEXT_SET:%3 ```,DO_TEXT_SET:%4 ```,DO_TEXT_SET:%5 UN```)
#define Text_DialogBox(%0,%9,%1,%2,%3,%4,%5) PSF:_Text_DialogBox(%0,%9,%1,DO_TEXT_SET:%2 DO_MOVE|||,DO_TEXT_SET:%3 ```,DO_TEXT_SET:%4 ```,DO_TEXT_SET:%5 UN```)
``````

Thank you

**Comment by Y-Less** [comment]
You might want to indent that code with 4 spaces in your comment - the backtick is also Github's inline code marker, hence the strange formatting.  Indenting it all in that way will change it to a block of code and correctly display the ticks.

While I'm on the subject of github tips.  If you link to some lines of code, select the lines you want then press "y".  That will take you to those lines in the current commit instead of on HEAD.  Lines in HEAD change so the link in the future may point to the wrong code, but if you have an exact commit it will always be correct.

**Comment by Misiur** [comment]
I merged your commit because other users will benefit from it too.
