### ISSUE TITLE
||| meaning in macro

### ISSUE THREAD

**Issue by Dayrion** [pawn-lang/YSI-Includes#189]
Well, I recently asked Y_Less what ||| means. « ||| is just a symbol that isn't used anywhere else, and so can be detected in macros. »
Can I get more details about this?

**Comment by Y-Less** [comment]
Honestly there aren't many more details - that is what it is.  `|||` is not a valid operator.  Say you want to use some macro parameters, but you don't know how many:

```pawn
#define MACRO(%0,%1,%2,%3,%4) %0,%1,%2,%3
```

I want some of them, but I don't know how many.  You can't use `,` so you need another symbol to scan for.  So that macro would be:

```pawn
#define MACRO(%0|||%1) %0
```

Then it doesn't matter how many parameters you call it with, just put `|||` after the ones you want:

```pawn
MACRO(10, 50, 42, 11, 65 ||| 8, 12, 2)
```

So for example, if you are looping through all the parameters, I use that to mark which the curent parameter is.  I now prefer using `` ` `` and `$` since `|||` starts with `|`, which IS a valid symbol and so can appear in valid code, which actually causes a problem.  I originall chose `|||` because the three together are not valid, but that's not actually quite how the pre-processor works.  Instead it would see the first `|`, not see a second one, and assume the macro match had failed.
