### ISSUE TITLE
Command_SetDeniedReturn() in y_commands not working.

### ISSUE THREAD

**Issue by se16n** [pawn-lang/YSI-Includes#24]
Hello.

Seems like there is one more issue.

In y_commands method Command_SetDeniedReturn() is not working.

Trunk version.

``` pawn
#include <YSI\y_commands>

public OnPlayerConnect (playerid) {

    Command_SetDeniedReturn(false);

    return 1;
}
```

> error 017: undefined symbol "Command_SetDeniedReturn"

**Comment by Misiur** [comment]
Ok, so as of now those functions are listed as "to be ported" https://github.com/Misiur/YSI-Includes/commit/bcdecc4bb9a72e29eccfb4d2e1dcec10ae618c81

I'll see later today if simply porting old version will work, if tests pass I'll leave it as it is.

**Comment by Misiur** [comment]
@Y-Less is [Command_ErrorRet](https://github.com/Misiur/YSI-Includes/blob/4bf5c854796781a7bf3e083e77278da4738fbf1b/YSI_Visual/y_commands/impl.inc#L310) successor to `Command_SetDeniedReturn`?

**Comment by Y-Less** [comment]
No, `Command_ErrorRet` is an internal define using variables directly, which (because they are `static` means that it won't compile in user code.  It is just the internal way to get the correct return for a given problem.  `Command_SetDeniedReturn` set the `OnPlayerCommandText` return value when a command was not allowed to be used by a player - 0 to give them the default command not found message and 1 to fail silently (which would tell players that they command they aren't allowed to use at least exists, a fact that you may want to keep hidden).

There used to be a whole host of functions for displaying different messages and setting different returns in different situations - command doesn't exist, command exists but you can't use it (denied), command failed, etc.  These don't really exist any more, they were largely replaced by `OnPlayerCommandReceived` and `OnPlayerCommandPerformed`, which is why they take and return a much more expanded "success" parameter (though the returns are still relevant for that).  The major bug holding that approach up is that the command passed to the callbacks doesn't include the parameters.

**Comment by Misiur** [comment]
@se16n: Use `OnPlayerCommandReceived` and check `success` for `COMMAND_DENIED`. I think that should suffice. As for lack of parameters, if anybody wants that in future, we'll open a feature request issue to track that.
