### ISSUE TITLE
y_hooks calling convention

### ISSUE THREAD

**Issue by Misiur** [pawn-lang/YSI-Includes#33]
@Y-Less 

Let's take a look at this example code

``` pawn
#include <a_samp>
#define _inc_a_samp
// #define _DEBUG 7
#include <YSI\y_hooks>

DEFINE_HOOK_REPLACEMENT(Replacement, Rpl);

main () {
    MyCustomReplacement();
}

forward MyCustomReplacement();
public MyCustomReplacement()
{
    printf("Hello from custom replacement");

    return 1;
}

hook MyCustomRpl()
{
    printf("Hello from custom replacement HOOK!");
    return 1;
}
```

Pcode

```
CODE 0  ; 2df08
    proc    ; main
    ; line 8
    break   ; 2df0c
    ; line 9
    break   ; 2df10
    push.c 0
    call .MyCustomReplacement
    ;$exp
    zero.pri
    retn

    proc    ; MyCustomReplacement
```

How I think it works: y_hooks creates a new function containing the whole hookchain, and rewrites the address in publics table to point to that new function. So, calling the original function should call the new one instead. However unless the function is called via CallLocalFunction, it won't work. The question is: Is that because CLF uses publics table, and "normal" function calls are set in stone during compile time?

I thought I knew how functions are called, but I'm baffled.
I'm asking because of https://github.com/Pottus/Texture-Studio/issues/7 and to know more. 

Bonus question: are ALS hooks compatible with y_hooks?

**Comment by Y-Less** [comment]
You are exactly correct - normal calls jump to a specific address that we can't change, CLF uses an address in the AMX header that we can change.  The reason one can be changed and the other can't is simple - we only know where one of them is.  The AMX header is a fixed structure, that looks like (IIRC, if not, something very close):

``` pawn
enum PUBLICS_HEADER
{
    PUBLIC_ADDRESS,
    NAME_INDEX
}

new
    amxPublics[MAX_PUBLICS][PUBLICS_HEADER],
    amxNames[MAX_PUBLICS];
```

Once we use the index to get the name from the second table, this is basically equivalent to:

``` pawn
enum PUBLICS_HEADER
{
    PUBLIC_ADDRESS,
    NAME[32]
}

new
    amxPublics[MAX_PUBLICS][PUBLICS_HEADER];
```

This is the exact table that CLF uses, and what y_hooks looks in to with:

``` pawn
new idx = 0, ptr;
while ((idx = AMX_GetPublicPointer(idx, ptr, "@yH_")))
{
    // "ptr" is now the contents of "PUBLIC_ADDRESS" for
    // all functions whose name matches "@yH_" (via strfind).
    // (More accurately, we use "AMX_GetPublicPointerPrefix"
    // because it is faster in this case).
}
```

From there, it is very simple to rewrite the value stored in `PUBLIC_ADDRESS` for CLF to see the new one next time.

We can't do the same for regular calls because we don't know where they are - they are just anywhere in code at all.  Technically there ARE parts of YSI that scan through the whole of the code and do a find-and-replace on matching snippets.  The snippets are usually longer to ensure no false positives, but if you first asserted that none of the functions pointers had the same value as any OpCode, then this could be safe.

The assertion needs to be done for one reason, consider this code:

``` pawn
#emit CONST.pri 33
#emit ADD
```

`33` is (in 4.0 at least - but that's another matter relating to the fact that sadly I seem to have also rather short-sightedly deleted my complete PAWN documentation history) the value of `CALL`.  This code is perfectly legal, but if we were scanning the generated code cell-by-cell and encountered the sequence `33 44` it could be misinterpreted as `CALL <44>` despite the fact that it is actually `33; ADD` with an offset.

I was working on a whole new AMX code replacement system as part of y_cgen to replace several ad-hoc solutions scattered around, for example here:

https://github.com/Misiur/YSI-Includes/blob/8bdf76d5a17366e2813b4ec7623913fc4c6590ac/YSI_Coding/y_malloc/heapalloc.inc#L198-L212

The idea was to develop a callback system looking something like:

``` pawn
public OnBoundsOpcode(addr)
{
    AMX_Write(addr, OP_NOP);
    AMX_Write(addr, OP_NOP);
}
```

``` pawn
CGEN_FindReplace("OnBoundsOpcode", OP_BOUNDS, 0);
```

Or something like that, with wildcards allowed.

Currently, each instance of a code replacer individually scans the entire AMX, leading to potentially multiple full scans instead of combining them in to one.  Plus, the random solutions aren't that robust - if they are run in the wrong order they may read garbage code left over from a previous run, and may misinterpret OpCode parameters as OpCodes.

However, that's all theoretical at this point - right now, y_hooks doesn't scan the AMX for all relevant `CALL` opcodes.

**Comment by Y-Less** [comment]
There is a hybrid solution that fixes.inc uses to get around the problem - it actually went back an ALS version.  It is massively undocumented, but relies on the fact that when using states a function stub is generated, so this:

``` pawn
main()
{
    MyFunc();
}

MyFunc() <s:a>
{
}

MyFunc() <s:b>
{
}
```

Becomes (approximately - the generated code is better than what can be written here):

``` pawn
main()
{
    MyFunc_stub();
}

MyFunc_stub()
{
    if (s == a) MyFunc_a();
    else if (s == b) MyFunc_b();
}

MyFunc_a()
{
}

MyFunc_b()
{
}
```

This means that the ONLY place that `MyFunc_a` is called from in the ENTIRE mode is the `MyFunc_stub` function.  THAT function might be called from hundreds of places, but it is not possible to call the two implementations directly ever.  fixes.inc uses this as such:

``` pawn
/* 
 * CHAIN_ORDER
 * 
 * Allows y_hooks to call things in the correct order when it exists.
 */

#if !defined CHAIN_ORDER
    #define CHAIN_ORDER() 0
#endif

/* 
 * PRE_HOOK
 * 
 * A method of pre-hooking callbacks to still have them called before any ones
 * re-written by y_hooks.
 */

#define PRE_HOOK(%0) forward @CO_%0();public @CO_%0(){return CHAIN_ORDER()+1;}

PRE_HOOK(FIXES)
#undef CHAIN_ORDER
#define CHAIN_ORDER @CO_FIXES

/* 
 * _FIXES_IncludeStates
 * 
 * Define the "_ALS" states used by hooks.
 */

static stock _FIXES_IncludeStates() <_ALS : _ALS_x0, _ALS : _ALS_x1, _ALS : _ALS_x2, _ALS : _ALS_x3>
{
}

static stock _FIXES_IncludeStates() <_ALS : _ALS_go>
{
}

/* 
 * _FIXES_FORWARD
 * 
 * Forwards a hooked callbacks, and defines the default state implementations.
 */
#define _FIXES_FORWARD%0(%1); \
    forward%0(%1); \
    public%0(%1) <_ALS : _ALS_x0, _ALS : _ALS_x1> { return 1; } \
    public%0(%1) <> { return 1; }

/* 
 * OnGameModeInit()
 * 
 * Call "FIXES_OnScriptInit" if this is not a FilterScript.
 * 
 * FIXES:
 *     IS_FILTERSCRIPT
 *     AllowInteriorWeapons
 *     AllowTeleport
 */

public OnGameModeInit()
{
    state _ALS : _ALS_go;
    // Other callbacks follow a similar pattern.
    return FIXES_OnGameModeInit();
}

#if defined _ALS_OnGameModeInit
    #error _ALS_OnGameModeInit defined
#endif
#define _ALS_OnGameModeInit
#define OnGameModeInit(%0) FIXES_OnGameModeInit(%0) <_ALS : _ALS_go>

_FIXES_FORWARD FIXES_OnGameModeInit();
```

This results in the next real function in the ALS chain getting the `<_ALS:_ALS:go>` state, and if it doesn't exist then the default implementation created by `_FIXES_FORWARD` handles that state instead.  There are five potential states for the `_ALS` automaton - `go` and four irrelevant ones that just pad the numbers.

y_hooks uses the standard AMX header searches to find the function stub, and replaces it with calls to its new code.  It doesn't need to worry about the additional states as they are never valid.  For one they are never entered ever; and for two, even if they are they will just trigger an empty default implementation - so they and the state stub are totally removed.  This means that "fixes.inc" can use fast ALS hooks both with and without y_hooks.  Indeed, any library following this slightly convoluted pattern can:

First, establish inclusion order.  The `CHAIN_ORDER` macro allows y_hooks to determine what order various libraries were included in and so ensure that their hooks are called in a precise order.

``` pawn
// ALWAYS define these EXACTLY.
#if !defined CHAIN_ORDER
    #define CHAIN_ORDER() 0
#endif
#define PRE_HOOK(%0) forward @CO_%0();public @CO_%0(){return CHAIN_ORDER()+1;}

// These should be set to your prefix (here "FIXES").
PRE_HOOK(FIXES)
#undef CHAIN_ORDER
#define CHAIN_ORDER @CO_FIXES
```

This just sets up the states, even if they have already been set up - it doesn't matter.  The NAME of the automaton should remain `_ALS`.  Just use a custom function name, with two instances, and make them `static stock` to not appear in the final output.  This is purely to tell the compiler which states can exist as only one is ever set with `state`:

``` pawn
static stock _FIXES_IncludeStates() <_ALS : _ALS_x0, _ALS : _ALS_x1, _ALS : _ALS_x2, _ALS : _ALS_x3> {}
static stock _FIXES_IncludeStates() <_ALS : _ALS_go> {}
```

Helper macro, not required, but shows how the states should be distributed.  This ensures that `x0` and `x1` have a concrete implementation to bind this function to the `_ALS` automaton, and ensures that `x2` and `x3` always call the default implementation even if `go` doesn't:

``` pawn
#define _FIXES_FORWARD%0(%1); \
    forward%0(%1); \
    public%0(%1) <_ALS : _ALS_x0, _ALS : _ALS_x1> { return 1; } \
    public%0(%1) <> { return 1; }
```

Set the correct state.  Do this in every init function - the more the merrier!  If you have the only library using this technique, you HAVE to set it or everything breaks.  If you aren't the only one, don't rely on that fact and set it anyway - it doesn't matter how many times it is done (don't go overboard though by putting it in OPU):

``` pawn
state _ALS : _ALS_go;
```

Finally, call the next chain function.  You may notice that the macros are slightly simpler because we don't need to check that the next function exists - it ALWAYS exists because we have the default state implementation.  The real next one only comes in to play when the `go` state is set explicitly, which we do with the `#define`:

``` pawn
    return FIXES_OnGameModeInit();
}

#if defined _ALS_OnGameModeInit
    #error _ALS_OnGameModeInit defined
#endif
#define _ALS_OnGameModeInit
#define OnGameModeInit(%0) FIXES_OnGameModeInit(%0) <_ALS : _ALS_go>

_FIXES_FORWARD FIXES_OnGameModeInit();
```

Without the `_FIXES_FORWARD` macro, this would look like:

``` pawn
    return FIXES_OnGameModeInit();
}

#if defined _ALS_OnGameModeInit
    #error _ALS_OnGameModeInit defined
#endif
#define _ALS_OnGameModeInit
#define OnGameModeInit(%0) FIXES_OnGameModeInit(%0) <_ALS : _ALS_go>

forward FIXES_OnGameModeInit();

public FIXES_OnGameModeInit() <_ALS : _ALS_x0, _ALS : _ALS_x1> { return 1; } 
public FIXES_OnGameModeInit() <> { return 1; }
```

You can, of course, do other clever things to set the correct return values - fixes.inc just doesn't use the macro for `OnPlayerCommandText` because the macro always returns "1".

As I said, y_hooks explicitly looks for this pattern and incorporates it.  The call order for hooks becomes:
1. Special hooks, i.e. this technique.
2. y_hooks, i.e. `hook`.
3. Normal ALS hooks.
4. The final `public`.

This is a very strange and complex technique, but is surprisingly composable.  It just isn't really designed for standard consumption, just things that MUST come before other hooks, for which fixes.inc qualifies but not much else does (AC and streamer probably yes).

See this code in y_hooks:

https://github.com/Misiur/YSI-Includes/blob/8bdf76d5a17366e2813b4ec7623913fc4c6590ac/YSI_Coding/y_hooks/impl.inc#L267-L361
https://github.com/Misiur/YSI-Includes/blob/8bdf76d5a17366e2813b4ec7623913fc4c6590ac/YSI_Coding/y_hooks/impl.inc#L412-L439
https://github.com/Misiur/YSI-Includes/blob/8bdf76d5a17366e2813b4ec7623913fc4c6590ac/YSI_Coding/y_hooks/impl.inc#L443-L498

While I'm on the subject, did I ever document this little bit:

https://github.com/Misiur/YSI-Includes/blob/8bdf76d5a17366e2813b4ec7623913fc4c6590ac/YSI_Coding/y_hooks/impl.inc#L136-L146

It allows you to write:

``` pawn
HOOK_RET:OnMyCallback()
{
    return 0;
}
```

To set the default return for callbacks when they aren't just "1" (but apparently they can only be "0" or "1", not say "42").

**Comment by Y-Less** [comment]
Well that was a longer response than I expected.  The shorter answer would have been:

> Yes.  No.

Of course, "no" still isn't right as ALS IS compatible with y_hooks, just not when used as an entry point instead of `CLF`/`CRF` by custom libraries.

**Comment by Y-Less** [comment]
I feel I should elaborate a bit more on this magic:

``` pawn
static stock _FIXES_IncludeStates() <_ALS : _ALS_x0, _ALS : _ALS_x1, _ALS : _ALS_x2, _ALS : _ALS_x3> {}
static stock _FIXES_IncludeStates() <_ALS : _ALS_go> {}
```

First, I'll elaborate a bit on how states ACTUALLY work.  A function looks like this:

``` pawn
MyFunc()
{
}
```

And compiles to this:

``` asm
PROC ; MyFunc

RETN
```

Every function starts with `PROC` and ends with `RETN` - the former sets up the stack and the latter jumps back to the place where the function was called from.

A state function looks like this:

``` pawn
MyFunc() <my_state : a>
{
}

MyFunc() <my_state : b>
{
}
```

Earlier I said this compiled to:

``` pawn
MyFunc()
{
    if (my_state == a) MyFunc_a();
    else if (my_state == b) MyFunc_b();
}

MyFunc_a()
{
}

MyFunc_b()
{
}
```

It is not QUITE that simple - the stub is not a normal function and doesn't have entry/exit.  It also uses a switch and converts to constants.  So this is more like:

``` asm
SWITCH my_state, 2 ; MyFunc
CASE 0, MyFunc_a
CASE 1, MyFunc_b

PROC ; MyFunc_a
RETN

PROC ; MyFunc_b
RETN
```

We have five states - `_ALS_x0`, `_ALS_x1`, `_ALS_x2`, `_ALS_x3`, and `_ALS_go`.  The forward macro (or code) from above generates:

``` pawn

forward FIXES_OnGameModeInit();

public FIXES_OnGameModeInit() <_ALS : _ALS_x0, _ALS : _ALS_x1> { return 1; } 
public FIXES_OnGameModeInit() <> { return 1; }
```

States `_ALS_x0`, `_ALS_x1` map to the first implementation.  States `_ALS_x2`, `_ALS_x3` map to the default implementation because they are never used explicitly.  If state `_ALS_go` IS used explicitly (by the user's hook) then it will map to that explicit function.  If it ISN'T used explicitly, it will map to the default function as well.

This gives us two possible situations.
1. WITH a next hook:

``` pawn
switch (_ALS)
{
    case _ALS_go: RealNext();
    case _ALS_x0: Dummy1();
    case _ALS_x1: Dummy1();
    default: Dummy2();
}
```
1. WITHOUT a next hook:

``` pawn
switch (_ALS)
{
    case _ALS_x0: Dummy1();
    case _ALS_x1: Dummy1();
    default: Dummy2();
}
```

Each case in the assembly is separate, hence why I made each case above separate when you could use `case _ALS_x0, _ALS_x1:`.

y_hooks examines the switch table here:

https://github.com/Misiur/YSI-Includes/blob/8bdf76d5a17366e2813b4ec7623913fc4c6590ac/YSI_Coding/y_hooks/impl.inc#L443-L498

The inner-most piece is this:

https://github.com/Misiur/YSI-Includes/blob/8bdf76d5a17366e2813b4ec7623913fc4c6590ac/YSI_Coding/y_hooks/impl.inc#L470-L481

It looks at the number of `case`s in the switch.  If there are two, there is no real next function.  If there are three, there is a real function and it figures out which it is.  This is why there are TWO calls to the dummy function - they both call the same function, so the two cases that are identical must be the dummy function and the remaining call must be the real one.

This is why there are five states not three.  Technically you could have four - two to map to the same dummy function, one for real use, and one to always map to (and thus justify the existence of) the default implementation (actually that one might be optional as well).  But there are five for symmetry - two for dummy function detection, two to prevent default function elision, and `go` for actually calling real code (or the default function when there isn't real code).

I said I would elaborate on the code at the start - you have to let the compiler know all possible states, that's all those functions do.  If your hook doesn't have a real "next", then no `<_ALS : _ALS_go>` function will exist for that callback.  If that is the ONLY callback, then you will get an error on `state _ALS : _ALS_go;` because that state isn't declared anywhere, so it must be pre-declared.  If you don't have a next function in the ALS hook chain, it doesn't matter at all.  The state is ALWAYS set to `_ALS_go`, but if there is no next function then there is no explicit implementation of that callback for that state, and so the fallback default (which does nothing but return) will be used.  I hope I've made that clear as I really don't think I have...

**Comment by Y-Less** [comment]
Also on this function:

https://github.com/Misiur/YSI-Includes/blob/8bdf76d5a17366e2813b4ec7623913fc4c6590ac/YSI_Coding/y_hooks/impl.inc#L443-L498

It checks the first instruction of a function.  As I said, all functions start with `PROC`, unless they are state handler stubs.  This makes it very simple to detect that a function is a state stub simply because the first instruction will instead be `LOAD.pri` (to load the variable holding the state's value - they are literally just globals once compiled).  The other detected case is `JUMP`, but that can only happen when y_hooks is in use because it replaces the stub with a jump to the new generated stub (and it shouldn't ever be seen as that would imply y_hooks was doing its work twice).

Replacing this stub with a jump is how y_hooks can support being hooked in to these special ALS chains despite the fact that they don't use CLF.  It also uses their order to determine WHICH stub to redirect to itself.  Note that it rewrites ALL the stubs it encounters - because `_ALS` is always `_ALS_go`, there is no real need for the switch, so the code gets optimised to a single jump to the next function in the chain.  Once the last special pre-hook has been run (again, determined based on the function name combined with `PRE_HOOK`), its "next" call stub is redirected to the y_hooks generated code.  If there was an original "next" function that is set to be the last thing the y_hooks function stub calls.  In this way, y_hooks inserts itself in to the MIDDLE of a local function call chain, instead of a public function call chain.

**Comment by Y-Less** [comment]
Also, while it makes sense for anyone using this pattern to use the exact `_ALS` automaton shown here, there is actually no reason why you can't use a custom one per library.
