### ISSUE TITLE
[5.x][y_hooks] Hook replacements not working?

### ISSUE THREAD

**Issue by Plastikmensch** [pawn-lang/YSI-Includes#391]
So, this gives me "undefined symbol EnableSBForPlayer" error:
```
DEFINE_HOOK_REPLACEMENT__(StuntBonus, SB);
hook function EnableSBForPlayer(playerid, enable)
{
    //some code
}
```
Letting me suspect that hook replacements aren't working, or in this case it doesn't.
Tried several variations and it makes no difference. 
When I remove the first line and replace SB with StuntBonus, the expected truncated warning appears.

**Comment by Y-Less** [comment]
Hook replacements only work for normal callback hooks, i.e. `hook OnWhateverSB()`.  However, there's a different way to do them for this style hook:

```pawn
#define EnableSBForPlayer EnableStuntBonusForPlayer

hook function EnableSBForPlayer(playerid, enable)
{
    //some code
}
```

It is a bit harder as you have to do a separate define for every function, instead of just one for `SB`, but on the plus side it uses standard language features instead of custom syntax.

**Comment by Plastikmensch** [comment]
Ah, thank you!
