### ISSUE TITLE
y_dialog_impl.inc error

### ISSUE THREAD

**Issue by realhus** [pawn-lang/YSI-Includes#429]
Hello, there is bug in YSI 5.
i used Y_Races on a blank (bare) script.

```
#include <a_samp>

#define YSI_NO_HEAP_MALLOC

#include "subscripts\YSI5\YSI_Visual\y_races.inc"

public OnPlayerSpawn(playerid)
{
	ShowPlayerDialog(playerid,1,DIALOG_STYLE_INPUT,"test","test","test","test");
	return 1;
}

```

Im getting this error
```
subscripts\YSI5\YSI_Visual\y_races\..\..\YSI_Players\y_text\..\..\YSI_Visual\y_dialog\y_dialog_impl.inc(182) : error 035: argument type mismatch (argument 4)
```

And warnings 

```
subscripts\YSI5\YSI_Visual\y_races\..\..\YSI_Players\y_text\y_text_impl.inc(570) : warning 203: symbol is never used: "str"


subscripts\YSI5\YSI_Visual\y_races\..\..\YSI_Players\y_text\y_text_impl.inc(570) : warning 203: symbol is never used: "file"

subscripts\YSI5\YSI_Visual\y_races\..\..\YSI_Players\y_text\y_text_impl.inc(592) : warning 203: symbol is never used: "name"
```

**Comment by TamerGezici** [comment]
The new PAWN libraries are doing constant correction so that they can be compatible with the new community compiler. Update your includes (including your SA-MP includes) link [here ](https://github.com/pawn-lang/samp-stdlib )or just change ShowPlayerDialog by hand.

This means you must change the parameters of ShowPlayerDialog which take strings to const. Also, if you are using any includes/code which by any chance also redefines or hooks ShowPlayerDialog, the same applies.

For example: 

`native ShowPlayerDialog(playerid, dialogid, style, const caption[], const info[], const button1[], const button2[]);`
