### ISSUE TITLE
Where documentation for YSI-Includes can be found?

### ISSUE THREAD

**Issue by SelfRecursion** [pawn-lang/YSI-Includes#510]
Hello there, 

I have a friend that is using Y-ini, he seems to have learned how to use it last year, but he's currently experiencing some difficulties using it in a filterscript, so I decided to try and help him out. I've been looking for any documentation about Y-Includes and Y-ini but without luck so far. I've obviously stumbed upon the [Wiki Section](https://github.com/YSI-Storage/y_ini/blob/dev/YSI-Storage/y_ini.md) but when I attempt to read about Y-ini, or any other Y-Includes module, it appears to be empty!

Does anyone knows where can I find any documentation about this?

**Comment by SelfRecursion** [comment]
After some further research, I've found some explanations on **how to use Y-ini** in here:
https://github.com/pawn-lang/YSI/blob/master/documentation/y_ini.txt

**Comment by Crayder** [comment]
Most modules' functions are listed and described in an `api.md` file (in their respective folder). This file has all of the documentation for functions from the modules. For example, `y_ini` has this file here: https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Storage/y_ini/api.md

Along with this some of the modules have a `quick-start.md`, `faqs.md`, and multiple test files to look at for reference. `y_iterate` is largely documented, see the y_foreach folder: https://github.com/pawn-lang/YSI-Includes/tree/5.x/YSI_Data/y_foreach

Otherwise, there are a few threads on [burgershot](https://www.burgershot.gg/) and a lot of people willing to help in the [Discord](https://discord.gg/2nFPkaZ).

**Comment by Y-Less** [comment]
As a general rule there's a `.md` file with the same name as the library that links you to the other files.  So for y_ini it's y_ini.md:

https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Storage/y_ini.md
