### ISSUE TITLE
y_circular error

### ISSUE THREAD

**Issue by 6krbn9** [pawn-lang/YSI-Includes#538]
```
#include "a_samp"
#include "YSI\y_ini"
#include "YSI_Data\y_circular"
#include "YSI\y_timers"
#include "sscanf2"
#include "progress"
#include "zcmd"
#include "mSelection"
#include"weapon-config"
#include "streamer"
#include "foreach"

static logBuffer[4][lEnum];

main()
{
	Circular_Init(logBuffer);
}
```
I get an error. (error 017: undefined symbol "cellbytes" on Circular_Init(logBuffer))

**Comment by Y-Less** [comment]
Well you must be on an old version because `YSI\y_ini` hasn't worked for a long time.  It's `YSI_Storage\y_ini`.

I'm actually not sure how you've managed this - y_circular was made long after the switch to the more organised folder layout.  Are you just copying random files around?  In which case, that's the problem.  Please check if this still happens on the latest correct version.
