### ISSUE TITLE
y_iterate counting extension?

### ISSUE THREAD

**Issue by BitFros7y** [pawn-lang/YSI-Includes#54]
Hey guys i have been making mini game for my server and i came to need a bit of "counting" items in foreach. I have ChasePlayer iterator, its for players but it can contain maximum of 16 players (mini game slots limit). Now i have 16 spawn points in array and i just want to read them in order i loop players.

new count = 0;
foreach(new chaseplayer : ChasePlayers)
{
    //SetPlayerPos(chaseplayer, SpawnPosX[count], ... (Something like these)
    count++;
}

In php i could use  foreach(ChasePlayers as chaseplayer => count)
So why not extend our foreach to be able to use these style with counting? I could (and probably will) create some dirty define to use it in that fashion but i guess a suggestion here doesnt hurt ether.

**Comment by Crayder** [comment]
This will most likely never happen. If you haven't noticed, the current syntax is based on C++'s foreach (which also happens to be quite similar to Java's foreach). Pawn is not to be compared with PHP in any way. It is very comparable to C++ though because it is based on C++.

**Comment by BitFros7y** [comment]
I chose php as example of what i mean. I just like that approach.

**Comment by Y-Less** [comment]
Doing that would be very complicated.  However, a middle-ground would be a feature that maybe should have been in foreach anyway:

``` pawn
foreach (new i : Player, b)
{
    ++b;
}
```

I'm not sure which syntax makes more sense - that one makes it quite explicit that `i` is bound to `Player`, but this way keeps all the variables more obviously together and the thing being iterated over on the right:

``` pawn
foreach (new i, b : Player)
{
    ++b;
}
```

Honestly I prefer the second one but it is not immediately obvious whether `i` or `b` holds the player value...  The second one is also much easier to code (I think, but that should never be a deciding factor).

None of this is up to me anymore though.

Any of course, once you start going in to these realms, you start muddying the waters between `for` and `foreach` - the former being general and the latter being specialised.  If you start adding features like that, people will want more and more of `for` to be added ad-hoc.  `foreach` already has support for the full range of `for` features by unwrapping the macro:

``` pawn
for (new i = Iter_Begin(Player), b; (i = Iter_Next(Player, i)) != Iter_End(Player); ++b)
{
}
```

A little verbose I know - sorry...

``` pawn
#define START(%0,%1) %0 = Iter_Begin(%1)
#define END(%0,%1) (%0 = Iter_Next(%1, %0)) != Iter_End(%1)

for (new START(i, Player), b; END(i, Player); ++b)
{
}
```

**Comment by BitFros7y** [comment]
These would be perfect
`foreach (new i : Player, b)`

And why would these be way easier to implement?

```
foreach (new i, b : Player)
```

If second one is more simple to implement, cant we implement it, and then use plain simple macro to mask it as first one? I know you said its not up to you, take it as how would you do it? 

And by the way, if i seem like i know what im talking about, believe me its not the case :smile:
So any advice you could provide is more then welcome.

**Comment by Y-Less** [comment]
The second one is simpler because it reuses the macros already there that split up the operation on `:`, so everything to the left is variables and everything to the right is the iterator.  Having variables on both sides makes the macros far more complex to pull everything together.  Unfortunately, there isn't a simple single macro to map one to the other as you say because of the number of macros already involved.

These macros detect the different "foreach" syntaxes that already exist:

https://github.com/Y-Less/YSI-Includes/blob/079751ba5746ac28d0de182e4bc137dff69bc9d1/YSI_Data/y_foreach/impl.inc#L823-L853

These include:

``` pawn
foreach (new i : Player) {}

new j;
foreach (j : Player) {}

foreach (Player, k) {}

foreach (new Float:f : FloatIter) {}
```

This macro adds reverses:

https://github.com/Y-Less/YSI-Includes/blob/079751ba5746ac28d0de182e4bc137dff69bc9d1/YSI_Data/y_foreach/impl.inc#L292

``` pawn
foreach (new m : Reverse Player) {}
```

(I don't actually remember WRITING that macro...)

These macros detect the different iterator types once the iterator location and direction has been determined:

https://github.com/Y-Less/YSI-Includes/blob/079751ba5746ac28d0de182e4bc137dff69bc9d1/YSI_Data/y_foreach/impl.inc#L783-L811

``` pawn
foreach (new i : Player) {}

foreach (new i : PlayerVehicle[2]) {}

foreach (new i : PlayerObject[2][4]) {}

foreach (new i : OtherThing<5>) {}

foreach (new i : FinalThing[2][4]<9>) {}
```

These macros strip excess spaces.  The old version didn't like `foreach ( new i : Player )` instead of `foreach (new i : Player)`.  This new version likes any spacings:

https://github.com/Y-Less/YSI-Includes/blob/079751ba5746ac28d0de182e4bc137dff69bc9d1/YSI_Data/y_foreach/impl.inc#L732-L755

These are just helper macros:

https://github.com/Y-Less/YSI-Includes/blob/079751ba5746ac28d0de182e4bc137dff69bc9d1/YSI_Data/y_foreach/impl.inc#L757-L781

I will say that MOST of the macros have a consistent input format.  The first set of macros that detect different syntaxes are the ones you need to look at - they convert the different inputs in to the correct format for the other macros.  That is why the second version is simpler, because you won't need to touch those first macros because the overall syntax hasn't changed (but I may be wrong).

The MOST simple may be a hybrid of sorts - require that the iterator variable is always last:

``` pawn
foreach (new b, i : Player)
{
}
```

It becomes clearer to which variable the iterator is assigned (the one next to it), keeps the simpler to write syntax, and solves some other implementation problems.

**Comment by Y-Less** [comment]
If you went with the final syntax (the second syntax with an ordering restriction), then currently the macros will expand to something like:

``` pawn
for (new b, i = Iter_Start(Player); _:(b, i = Iter_Next(Player, b, i)) != Iter_End(Player); )
{
}
```

Everywhere that `i` appears `b, i` will appear instead.  There is a tag override in the condition (`_:`).  This is added by these lines, to which you could add an additional tag:

https://github.com/Y-Less/YSI-Includes/blob/079751ba5746ac28d0de182e4bc137dff69bc9d1/YSI_Data/y_foreach/impl.inc#L795-L811

Use that to detect and strip out additional variables recursively, but for all the different syntaxes.

**Comment by Y-Less** [comment]
Not doing this.
