### ISSUE TITLE
y_testing result passes even if the condition fails

### ISSUE THREAD

**Issue by tianmetal** [pawn-lang/YSI-Includes#95]
Take a look at this code

```
#include <a_samp>
#define YSI_TESTS
#include <YSI\y_testing>

main() { }

stock ThisFunctionFails(index)
{
    new someArray[2];

    someArray[index] = 5;
}

Test:ThisTestAlwaysSuccess()
{
    new pass = 1;
    ThisFunctionFails(2); // out of bounds
    ASSERT(pass == 0);
}
```

We can see that function `ThisFunctionFails` will produce Out of bounds error on runtime but the test case will pass anyway

> [14:32:01] **\* Test ThisTestAlwaysSuccess start
> [14:32:01] PASS!

if we remove `ThisFunctionFails`, the test will fail

> [14:32:57] **\* Test ThisTestAlwaysSuccess start
> [14:32:57] FAIL: "pass == 0"

it took me a while to realize that y_testing was causing this issue while debugging

**Comment by Y-Less** [comment]
There's not a huge amount that can be done about that, since out-of-bounds array accesses are undefined behaviour, unexpected results are likely.  If you compile with `-d3` there will be `BOUNDS` OpCodes in the code and the array accesses will be checked at least to give a run-time error.  The only thing that could be done then would be to use the CrashDetect plugin's callbacks to generate a test fail on runtime errors.

**Comment by Y-Less** [comment]
Improved crash-detect integration in #101, you should really be using as high debug level as possible when running tests, so I'd count this as done.
