### ISSUE TITLE
y_malloc

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#98]
When starting the server, this error is coming up

[18:07:16] **\* YSI Error: heapspace too low for y_malloc: Did you use "#pragma dynamic"?
[18:07:16] **\* YSI Warning: y_malloc set up via "CallLocalFunction", memory corruption is a remote possibility
[18:07:16] Script[gamemodes/test.amx]: Run time error 3: "Stack/heap collision (insufficient stack size)"

Could you please indicate the problem ?

Thanks

**Comment by Y-Less** [comment]
Have you read the messages?

**Comment by ghost** [comment]
Hello, 
Sure, I read them about :  Did you use "#pragma dynamic"
The answer was yes, after seeing this, i directly removed it and tried again in vain. For others, messages, to be honest i didn't really understood them or don't really know what i could do. (that's why i came here for more explanations)

Edit: I add this crashlog (compilied with -d3)
[crashlog.txt](https://github.com/Misiur/YSI-Includes/files/298856/crashlog.txt)

**Comment by ghost** [comment]
Resolved- thanks Misiur

**Comment by Y-Less** [comment]
What changed?  I was going to say you may need a larger dynamic size, but if there was another solution I'd be interested in hearing it.

**Comment by ghost** [comment]
my bad, a #pragma dynamic was hidden in a include included in another include
Thanks however for taking time to look at this

**Comment by Y-Less** [comment]
Yes, y_malloc uses "#pragma dynamic" to increase the heap space.  It used to use a huge global array, which was simpler, but took longer to compile and produced huge .amx files, then people complained.  The new version uses a define in the dynamic declaration, but if you use another one elsewhere there is no way to detect it.  That would actually be a good new compiler warning - using that directive twice in one program should be alerted to.

I've tried before to figure out a way to detect when another one is used, but haven't managed.

**Comment by ghost** [comment]
Currently, the server is starting correctly but meet few problems even if you can connect corretly:

http://pastebin.com/DCz5DwqU

It is similar to this issue:
https://github.com/Misiur/YSI-Includes/issues/86

I also have this warning:

E:\test\pawno\include\YSI..\YSI_Coding..\YSI_Data\y_iterate.inc(229) : warning 201: redefinition of constant/macro (symbol "_FOREACH_CUR_VERSION")

**Comment by Misiur** [comment]
Make sure you have latest crashdetect - https://github.com/Zeex/samp-plugin-crashdetect/releases , then try again and tell us if some of the errors went away

**Comment by ghost** [comment]
Indeed, some errors went away. However these one are still here

```
[19:07:01] [debug] Run time error 3: "Stack/heap collision (insufficient stack size)"
[19:07:01] [debug]  Stack pointer (STK) is 0x152A2C0, heap pointer (HEA) is 0x15ABA88
[19:07:01] [debug] AMX backtrace:
[19:07:01] [debug] #0 00110348 in LoadVehicles () at C:\Antoine\Documents\test\gamemodes\test.pwn:14080
[19:07:01] [debug] #1 000886c4 in public zcmd_OnGameModeInit () at C:\Antoine\Documents\test\gamemodes\test.pwn:4342
[19:07:01] [debug] #2 native CallLocalFunction () from samp03svr
[19:07:01] [debug] #3 000652d8 in public IRC_OnGameModeInit () at C:\Antoine\Documents\test\pawno\include\zcmd.inc:98
[19:07:01] [debug] #4 native CallLocalFunction () from samp03svr
[19:07:01] [debug] #5 000649a8 in public SSCANF_OnGameModeInit () at C:\Antoine\Documents\test\pawno\include\irc.inc:204
[19:07:01] [debug] #6 0005dae4 in public ScriptInit_OnGameModeInit ()  at C:\Antoine\Documents\test\pawno\include\sscanf2.inc:205
[19:07:01] [debug] #7 00002b68 in public OnPlayerPickUpDynamicPickup (playerid=0, pickupid=0) at C:\Antoine\Documents\test\pawno\include\YSI\..\YSI_Storage\..\YSI_Internal\..\YSI_Server\y_scriptinit.inc:184
```

I also precise that the warning is not here when compiling with the basic compiler (i used zeex compiler)

pawno\include\YSI..\YSI_Coding..\YSI_Data\y_iterate.inc(229) : warning 201: redefinition of constant/macro (symbol "_FOREACH_CUR_VERSION")

**Comment by Y-Less** [comment]
I don't know why you get that redefinition warning - it shouldn't happen even with very old versions of "foreach" installed in parallel.  Delete "foreach.inc" and see if that solves it.

As for the other issue, put this at the very top of your mode:

``` pawn
#define MALLOC_MEMORY (32 * 1024 * MALLOC_KB_TO_CELL)
```

I don't actually think that will help if the problem is what I actually think it is.  If that doesn't solve it, the problem is because "y_malloc" uses some of the heap, and reserves that section for private use, the remainder is for the normal heap and stack.  This normal heap/stack space is what you normally set up with:

``` pawn
#pragma dynamic 65536
```

Or whatever the size is.  Can you remeber what those other `#pragma dynamic`s were set to?  I suspect the issue is that this extra area needs increasing, while that define I gave you above will only increase malloc's area.  ["y_malloc.inc" includes this:](https://github.com/Misiur/YSI-Includes/blob/f1b57c293a09a9f3c43e36f6b6cf7798efb5f45c/YSI_Coding/y_malloc.inc#L164)

``` pawn
#pragma dynamic MALLOC_MEMORY + 65536
```

That allocates space for "y_malloc", plus some more for other uses.  Unfortunately, if your other uses need more than that, there's currently no easy way to specify this.  I should make it something like:

``` pawn
#if !defined DYNAMIC_MEMORY
    #define DYNAMIC_MEMORY (65536)
#endif
#pragma dynamic MALLOC_MEMORY + DYNAMIC_MEMORY
```

For now, try changing that line (currently line 164 of "y_malloc.inc") to something like:

``` pawn
#pragma dynamic MALLOC_MEMORY + 131072
```

Or frankly any other number until it doesn't crash (the smaller the better).

**Comment by Y-Less** [comment]
I set that number to something large - way bigger than the default stack already is, so this is the first time that it has happened that what I changed it to wasn't large enough.

**Comment by ghost** [comment]
Thank for all those informations, i tried : #define MALLOC_MEMORY (32 \* 1024 \* MALLOC_KB_TO_CELL) but the errors are still.

when i had #pragma dynamic it was : #pragma dynamic 556992

**Comment by Y-Less** [comment]
Right, well use that number in place of `65536` in the include.  As I say, this is something that should be configurable at compile-time, but currently isn't, so you have to edit the file directly.

**Comment by ghost** [comment]
I tried with 

`#pragma dynamic MALLOC_MEMORY + 131072`

But it didn't worked. As a consequence i put a big number, those errors disappeared, then i reduce it and it also not here.

`#pragma dynamic MALLOC_MEMORY + 205000`

However, im wondering if because of this my cars are not loading entirely

**Comment by ghost** [comment]
Alright, after several tests. It doesn't affect the cars as i thought, it was an intern problem. Thank you for the solution, it is working good.

**Comment by Y-Less** [comment]
I suggest you add this to the very top of your mode now:

``` pawn
#define DYNAMIC_MEMORY <whatever number you chose>
```

Just as a bit of future-proofing.  I'll update it very soon (I have a few changes to upload anyway), and use that define instead of the constant number as I discussed above.  Otherwise it may suddenly break again if you update YSI, and if that isn't soon you could have forgotten about this chat.

**Comment by ghost** [comment]
Okay, thank you I close the issue. So, as if i understand correctly in a future update we will be able to define it in our gamemodes as we want ?
Again thanks for the help provided

**Comment by Y-Less** [comment]
OK, I've added that define in to my local version.  I also found a way to break `#pragma dynamic <num>` for all future uses (i.e. ones after including "y_malloc") - the part after `#pragma` is actually subject to pre-processor replacements, so I redefine `dynamic` to something else - this breaks the pragma, but if anyone ever uses it as a variable it will still work fine (with a different name).  There seems to be an overflow in the `#pragma` part of the compiler, which is convenient, as it means I can actually inject some slightly useful text in to the error message.  I added this code to "y_malloc":

``` pawn
// ========================================================================== //
//                                                                            //
//                                 IMPORTANT!                                 //
//                                                                            //
// ========================================================================== //
#define dynamic dynamic_is_now_DYNAMIC_MEMORY_                                //
// ========================================================================== //
//                                                                            //
// dynamic_is_now_DYNAMIC_MEMORY_                                             //
//                                                                            //
// If you get a warning or error about "dynamic_is_now_DYNAMIC_MEMORY_",      //
// hopefully (though doubtfully) you searched for something related to it and //
// found this.  If you are slightly confused, just remember that any          //
// reference to that variable is actually a reference to a variable called    //
// "dynamic", and so the error/warning refers to that.                        //
//                                                                            //
// _is_now_DYNAMIC_MEMORY_                                                    //
//                                                                            //
// If you get an error or warning about "_is_now_DYNAMIC_MEMORY_", it is      //
// because you have tried to use "#pragma dynamic <number>" after including   //
// "y_malloc" (or another library that eventually includes "y_malloc").       //
// Because that library allocates memory from the heap, it needs control over //
// how much memory is in the heap to begin with.  You do this with            //
// "#pragma dynamic <number>", which that library does.  Because using that a //
// second time somewhere in your mode will break "y_malloc", it disables the  //
// pragma, and instead outputs that error.  If you need to increase your      //
// stack or heap size (due to a stack/heap collision), add this to the very   //
// top of your mode:                                                          //
//                                                                            //
//   #define DYNAMIC_MEMORY <number>                                          //
//                                                                            //
// ========================================================================== //
```

The error looks something like:

```
C:\file.pwn(18) : error 017: undefined symbol "_is_now_DYNAMIC_MEMORY_"
```

The warning is just because of code like this:

``` pawn
MyFunc(dynamic)
{
    return 1;
}
```

Which will still work and compile, but will give this warning:

```
C:\file.pwn(19) : warning 203: symbol is never used: "dynamic_is_now_DYNAMIC_MEMORY_"
```

Instead of this warning:

```
C:\file.pwn(19) : warning 203: symbol is never used: "dynamic"
```

If you use the variable, then everything will be fine.
